### ISSUE TITLE
Comma in ID causes errors

### ISSUE THREAD

**Issue by dukedave** [composite-primary-keys/composite_primary_keys#399]
See these [regression tests](https://github.com/composite-primary-keys/composite_primary_keys/commit/ad4c377b52f9e17bf325c1ae84590a2490b3625b).

I believe the issue stems from the [`normalize`](https://github.com/composite-primary-keys/composite_primary_keys/blob/b99417c1896f028ce2ff396a947acd79dd20828d/lib/composite_primary_keys/composite_arrays.rb#L14) method calling itself recursively.
I wonder if, in the case that the caller passes an array to `find`, we should just assume all the IDs have already been normalized?

**Comment by dukedave** [comment]
I do seem to be able to work around this by changing `ID_SEP` in [an initializer file](http://guides.rubyonrails.org/configuring.html#using-initializer-files), e.g:

```
# config/initializers/composite_primary_keys.rb
module CompositePrimaryKeys
  ID_SEP = '###'
end
```
Are there any side effects to this?

**Comment by cfis** [comment]
Yeah, I would think that would break a lot of things.

You can't accomplish what you want because CPK supports this usage.

ReferenceCode.find('1,2')  

I've never liked that style, but it was put in the very first version of CPK.  I suspect if that support is removed, then it will break someone's code.

Thus you could not have nested commas.  That is what the normalized code is for.  Now I u

**Comment by cfis** [comment]
Suppose to work around it, override the normalize method.
