### ISSUE TITLE
Problem when using with Rails' form helpers

### ISSUE THREAD

**Issue by fnordfish** [composite-primary-keys/composite_primary_keys#421]
When using Rails' `fields_for` FormHelpers/Builders, it
> will automatically generate a hidden field to store the ID of the record.

Which is good, since composite_primary_keys will make sure, that calling `id` will return the composite key information.
The bad part is, that Rails will convert a key `[1, 5]` to `"1 5"` (separated by a single space, instead of a comma). This is because `CompositePrimaryKeys::CompositeKeys` "is_a Array" and rails tag helpers convert Arrays to space separated lists (which makes sense for class attributes and alike) (see: https://github.com/rails/rails/blob/68a2888ef08faf38c0643921a8259beef5fbe630/actionview/lib/action_view/helpers/tag_helper.rb#L88)

My current workaround is to monkey patch rails and explicitly test for `CompositePrimaryKeys::CompositeKeys` values, calling `to_s` on them.

Is there a way to let CompositeKeys not inherit Array, avoiding those kind of issues?

**Comment by cfis** [comment]
Hmm, I suppose.  But first time this has come up.  Want to create a patch?

**Comment by fnordfish** [comment]
@cfis I think combing them not that of a common use-case, although it might be the last issue over at rails_admin.
Anyways, I'd be happy to come up with a patch. I just wanted to make sure, that there is nothing important that depends on `CompositeKeys` being a subclass of `Array`.

**Comment by cfis** [comment]
Composite keys use a lot of array enumerable functionality - like #zip or #each or #map.  So you'd have to make sure all that works.  Then there a various checks is_a?(Array) that might need updating (usually composite keys end up as an Array not a CompositeKey - to hard to change every instance.

Then you'd want to do it on ActiveRecord 5.2 because ActiveRecord 5.1 is about wrapped up now.  You wouldn't be able to take a patch for 5.1 and apply it to 5.2, too many difference between release as per usual.

**Comment by cfis** [comment]
No response, closing.

**Comment by fnordfish** [comment]
Yah, sorry - Don't have much time either :( But thanks for your hints anyways. Maybe I'm going to revisit this (much) later. At least it might be useful for someone with the same issue.
