### ISSUE TITLE
early rails 7 testing

### ISSUE THREAD

**Issue by jasonkarns** [composite-primary-keys/composite_primary_keys#562]
We dual-boot Rails to make version upgrades painless. Now that 6.1 has been released for a bit, we're preparing to dual boot with the 7.0 (alpha) release from github master.

However, we can't presently resolve our dependencies because CPK is pinned to 6.1.

Can CPK master branch relax the version constraint so interested teams can get a head start on using CPK with Rails 7?

(Or if not master, then an separate branch?)

**Comment by codeodor** [comment]
@jasonkarns I am unable to think through the ramifications for doing that on the master branch, but if you wouldn't mind, I would gladly accept a PR for whatever you need and make a new branch out of it. 

Sorry, I am just so swamped the last few months.

**Comment by cfis** [comment]
@jasonkarns - The dependency is intentional because every Rails upgrade breaks CPK.

Would be more than happy to welcome contributions to get CPK working with Rails 7, but those changes should be done in a separate branch.

**Comment by jasonkarns** [comment]
> The dependency is intentional because every Rails upgrade breaks CPK.

Right, but isn't that handled by the released gem's gemspec? I'd think that with breakages this common, we'd want CPK master capable of running against Rails master–to catch all the new breakages early and often? That way, end users can be running vnext dual-boot setups and, in essence, crowd-source CPK's integration suite.

In addition to getting the benefit of "in the wild" test coverage, CPKs own test suite would be running against latest Rails.

**Comment by cfis** [comment]
The problem is that ActiveRecord upgrades break a lot of stuff in CPK. Each upgrade requires going through each line of CPK, see how the underlying ActiveRecord implementation has changed, and then update CPK. Its a long, manual process.

**Comment by jasonkarns** [comment]
Right, I don't discount that this requires manual changes. I just fail to see what is gained by preventing users from running edge CPK against edge Rails. Allowing it would enable users to uncover breakage _before_ Rails is released instead of after. (It would also mean that triangulating the commits in Rails could be automated with a bisect script.)

I guess what it comes down to is: "Is it the policy of the CPK team that installing CPK _from github_ is a supported installation method and that is ensured to be stable with the latest release of Rails _from rubygems_?

That's the disconnect that I don't follow. Typically, master/main is expected to be "vnext" and is not a supported (stable) installation source.

To bring it back to practical terms: as it stands with CPK's gemspec, it is not possible for anyone to test their app against Rails master without forking CPK. That's a big pain point that makes it harder for teams to stay evergreen.

**Comment by cfis** [comment]
Because running edge against edge Rails doesn't work, there is nothing to be gained. And it is never a matter of a few fixes - its usually quite a lot of development.

Once work starts on Rails 7 support, a 6.1 branch will be created and then master will move to 7.0.

Happy to take contributions to get 7.0 support started!

**Comment by cfis** [comment]
Rails 7.0 support has been released in CPK 14.0.0 thanks to the work of @codeodor!

**Comment by codeodor** [comment]
@cfis could we maintain a separate branch for this? Re-reading it, I think I understand better what @jasonkarns  was talking about. I've often wanted to run CI against edge rails to be able to fix bugs before I get into upgrade mode, but it is near impossible due to dependencies. If we did this, someone might catch errors and put in PRs for them before we get to upgrading as a bulk process.

**Comment by cfis** [comment]
A separate branch for the next version of Rails? So a branch called edge? If that is what you mean, sure. 

I could see it being useful if over the course of a Rails development cycle each relevant change to ActiveRecord could then be propagated to CPK. Of course someone would have to be doing that....otherwise I don't really see the point. But its easy to create a branch and see.
