### ISSUE TITLE
ActiveRecord::StatementInvalid when calling delete_all on composite_primary_keys table

### ISSUE THREAD

**Issue by KidA001** [composite-primary-keys/composite_primary_keys#573]
We just upgraded to `Rails 6.1.5.1` from `5.2.6`. We have one model which uses Composite Primary Keys.

```ruby
class Reading < ApplicationRecord
  self.primary_keys = :account_id, :created_at, :source_type_id

  belongs_to :account

  ...
end
```

If I call `delete_all` on a AR Relation of readings (i.e. `Reading.all.delete_all` it throws the following error
```
 Reading Destroy (3.0ms)  DELETE FROM "readings" WHERE "readings"."account_id,created_at,source_type_id" IN (SELECT "readings"."account_id,created_at,source_type_id" FROM "readings" ORDER BY "readings"."created_at" DESC)
/Users/me/.rvm/gems/ruby-3.1.0/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params': PG::UndefinedColumn: ERROR:  column readings.account_id,created_at,source_type_id does not exist (ActiveRecord::StatementInvalid)
LINE 1: ..."account_id,created_at,source_type_id" IN (SELECT "readings"...
```

This was previously working in our older version of rails.

```
Ruby 3.1.0
Rails 6.1.5.1
composite_primary_keys 13.0.3
activerecord 6.1.5.1
```

Any help appreciated 🙏

**Comment by codeodor** [comment]
That said, any way you could submit a PR that has a test case that fails
for this? Even if I can't get to it quickly, @cfis might, and it would at
least make it easy to reproduce in the CPK code, which would reduce
friction if I do find some time to look into it.

**Comment by codeodor** [comment]
I remember running into something like this and making a workaround in my
code. I don't remember enough of the details to know where to look it up in
my codebase, but I am curious to know if it's still present in the latest
version on Rails 7 and I am keen to fix it if it is. (Or figure out how we
fixed it and backport it if it's not).

Unfortunately I am more than swamped over the last several months, and that
doesn't look to improve in the short term.

**Comment by KidA001** [comment]
@codeodor thank you for the response. I forked and tried creating a failing spec but so far no luck. That said I found some more info. It looks like `update_all` fails as well. Based on the message you posted I grep'd through the commits to see if I can find something and it looks like 1e238902e5a5df97eb344926869d5af6ccda3787 fixed this issue but not on Postgresql. Is this the fix you might have been referencing?

**Comment by cfis** [comment]
Hmm, there are tests for delete_all and update_all which pass (including postgresql). So I wonder what is different in your usage versus what the tests are doing?

**Comment by KidA001** [comment]
One difference I am seeing when I run `delete_all` in my old version of Rails and New version is in the new one (that's broken) it's doing a sub-select statement.

So for instance in my working version if I do
```ruby
Reading.where(val: 125..9999).delete_all
```
The sql it executes is:
```
DELETE FROM "readings" WHERE "readings"."val" BETWEEN $1 AND $2  [["val", 125], ["val", 9999]]
```

Whereas in my new Rails 6.1 it executes with a sub-select that should return the ID's for the IN statement which fails:
```sql
DELETE FROM "readings" WHERE "readings"."account_id,created_at,source_type_id" IN (SELECT "readings"."account_id,created_at,source_type_id" FROM "readings" WHERE "readings"."val" BETWEEN $1 AND $2 ORDER BY "readings"."created_at" DESC)
```

It doesn't consider `"readings"."account_id,created_at,source_type_id" ` a column. This seems to be the issue but why it's executing this way I don't know

**Comment by KidA001** [comment]
So I have "Fixed" the issue by changing the `if` statement for CPK from
```ruby
if @klass.composite? && @klass.connection.visitor.compile(stmt.ast) =~ /['"]#{primary_key.to_s}['"]/
```
to
```ruby
if (klass == Reading)
```
as `Reading` is our only CPK model


So now this is what executes:
```ruby
if (klass == Reading)
  stmt = Arel::DeleteManager.new
  stmt.from(arel_table)
  cpk_subquery(stmt)
else
  stmt.wheres = arel.constraints
end
```

I also had to move
```ruby
stmt.take(arel.limit)
stmt.offset(arel.offset)
stmt.order(*arel.orders)
```
above that statement otherwise it executes as an invalid SQL statement.

I did a similar patch for `update_all`

This is a temporary fix obviously, but I'm wondering if it gives any hints on your end  to the issue I might be having?

**Comment by cfis** [comment]
@codeodor - You added the regex check in the upgrade to Rails 6.1 (see https://github.com/composite-primary-keys/composite_primary_keys/commit/9035a54587d6dbbc5bf498a3ff507a5fa245ad90#diff-1965ba86b287586c5ee6c882683937891f693e0a923796a1ef5e12bf56f576cb). 

If I remove it, all tests still pass.

I'm not sure why the regex was added or is needed. Do you remember? Can we remove that check?

**Comment by codeodor** [comment]
I added it due to a major performance problem I was having with it: https://github.com/composite-primary-keys/composite_primary_keys/pull/504

Basically, a query that should have taken the form:

`delete from table where non_id = 30` 

Instead took the form:

`delete from table where (id1, id2) in (select id1, id2 from table where non_id = 30)` 

(or something like that)

The subquery caused a massive performance problem in our app, like taking minutes instead of less than one second. So I thought, why don't we only do this subquery where it is necessary.

**Comment by codeodor** [comment]
It could be that work we later did, or an upgrade of MySQL, has fixed the performance issue. If it's causing a problem here, I don't mind if we remove it, but ideally we'll add a test that fails with this code still included, that way if I discover the performance problem again, I would have to fix it in a way that won't break the code for someone else.

**Comment by cfis** [comment]
Yes, agreed having a test case would be really good. @KidA001 what database are you using? Anything in the CPK test models that looks like it could be used to reproduce the issue?

**Comment by cfis** [comment]
Realized we never fixed this. I'm going to remove the regex check on the basis that correctness is more important that faster performance.

**Comment by codeodor** [comment]
I have confirmed that `&& @klass.connection.visitor.compile(stmt.ast) =~ /['"]#{primary_key.to_s}['"]/` when present fixes our failing test case.

**Comment by codeodor** [comment]
Did we ever get a failing test case for this delete issue?

**Comment by codeodor** [comment]
Our issue (aside from the performance impact, which is huge) turns out to be an error due to allowing "null" in one of our "primary keys" so when we do a query like `where (one, two, three) in (select one, two, three from ...)` it won't match and therefore won't update/delete the correct rows, even though we may do something that needs no conditions, such as `Foo.delete_all`

I am not sure how to reconcile this in our application, as the table itself doesn't really have a natural key and we never added an integer key because it is constantly adding and removing millions of rows so I didn't want to run out of numbers (lol) back when ~4 billion was the size. At the same token, we did add this "key" in the Rails model as a way to help prevent duplicates when we did a select. 

Because of that, I will just add those two lines as a patch in our own app to ensure it continues to work and of course where it gives us a huge performance boost on some queries taking longer than 10 minutes vs. under one second any time we delete or update multiple rows in such a table.

**Comment by cfis** [comment]
What causes the performance issue? If it make sense to patch CPK of course go ahead.

**Comment by codeodor** [comment]
The cause of the performance issue is relying on the (key1, key2, key3... keyn) in (select key1, key2, key3...) when not necessary. That is what got removed to fix this one. So somehow what I targeted was too broad (intention was to see if it was needed and only use when needed -- but evidently I was broad since removing it fixed this issue).
